import copy
import gc
import logging
import queue
import threading
import re

from dataclasses import dataclass
from tqdm import tqdm
from typing import List, Optional, Tuple, Union

import torch
import transformers
from torch import Tensor
from transformers import set_seed
from scipy.stats import spearmanr

from nanogcg.utils import (
    INIT_CHARS,
    configure_pad_token,
    find_executable_batch_size,
    get_nonascii_toks,
    mellowmax,
)

logger = logging.getLogger("nanogcg")
if not logger.hasHandlers():
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s [%(filename)s:%(lineno)d] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


def log_loss_transform(thinking_length: float, scale_factor: float = 0.1) -> float:
    """
    使用对数变换将思考长度转换为损失值，范围在(0, 1]之间

    Args:
        thinking_length: 思考内容的token数量
        scale_factor: 缩放因子，控制对数变换的影响程度

    Returns:
        变换后的损失值，范围在(0, 1]之间，思考长度越长，损失越接近0
        当thinking_length=0时，损失为1.0；随着thinking_length增长，损失单调递减
    """
    # 使用 log1p(thinking_length * scale_factor) 避免log(0)问题
    # 损失 = 1 / (1 + log1p(thinking_length * scale_factor))
    transformed_loss = 1.0 / (1.0 + torch.log1p(torch.tensor(thinking_length * scale_factor)))
    return float(transformed_loss)


def extract_thinking_content(generated_text: str, start_tag: str = "<thinking>", end_tag: str = "</thinking>") -> str:
    """Extract content between thinking tags from generated text.

    Args:
        generated_text: The text generated by the model
        start_tag: The start tag (default: "<thinking>")
        end_tag: The end tag (default: "</thinking>")

    Returns:
        The content between thinking tags, empty string if no tags found
    """
    # Escape special regex characters in tags
    escaped_start = re.escape(start_tag)
    escaped_end = re.escape(end_tag)

    # Find content between start and end tags
    pattern = f'{escaped_start}(.*?){escaped_end}'
    matches = re.findall(pattern, generated_text, re.DOTALL)

    if not matches:
        return ""

    # Return the longest thinking content if multiple matches exist
    return max(matches, key=len)


@dataclass
class GCGConfig:
    num_steps: int = 250
    optim_str_init: Union[str, List[str]] = "x x x x x x x x x x x x x x x x x x x x"
    search_width: int = 512
    batch_size: int = None
    topk: int = 256
    n_replace: int = 1
    buffer_size: int = 0
    use_mellowmax: bool = False
    mellowmax_alpha: float = 1.0
    early_stop: bool = False
    use_prefix_cache: bool = True  # Enable prefix caching for better performance
    allow_non_ascii: bool = False
    filter_ids: bool = True
    add_space_before_target: bool = False
    seed: int = None
    verbosity: str = "INFO"
    max_generation_tokens: int = 200  # Maximum tokens to generate
    thinking_start_tag: str = "<thinking>"  # Customizable thinking start tag
    thinking_end_tag: str = "</thinking>"    # Customizable thinking end tag
    # Log loss transformation parameters
    loss_scale_factor: float = 0.01  # Controls log transformation intensity

    # Early stopping parameters
    consecutive_threshold: int = 3  # Number of consecutive times reaching max length to trigger early stop

    # Performance optimization parameters
    use_batch_generation: bool = True  # Enable batch text generation
    max_batch_size: int = 8  # Maximum batch size for batch generation to avoid OOM


@dataclass
class GCGResult:
    best_loss: float
    best_string: str
    losses: List[float]
    strings: List[str]


class AttackBuffer:
    def __init__(self, size: int):
        self.buffer = []  # elements are (loss: float, optim_ids: Tensor)
        self.size = size

    def add(self, loss: float, optim_ids: Tensor) -> None:
        if self.size == 0:
            self.buffer = [(loss, optim_ids)]
            return

        if len(self.buffer) < self.size:
            self.buffer.append((loss, optim_ids))
        else:
            self.buffer[-1] = (loss, optim_ids)

        self.buffer.sort(key=lambda x: x[0])

    def get_best_ids(self) -> Tensor:
        return self.buffer[0][1]

    def get_lowest_loss(self) -> float:
        return self.buffer[0][0]

    def get_highest_loss(self) -> float:
        return self.buffer[-1][0]

    def log_buffer(self, tokenizer):
        pass  # 主循环中已经输出了更详细的信息


def sample_ids_from_grad(
    ids: Tensor,
    grad: Tensor,
    search_width: int,
    topk: int = 256,
    n_replace: int = 1,
    not_allowed_ids: Tensor = False,
):
    """Returns `search_width` combinations of token ids based on the token gradient."""
    n_optim_tokens = len(ids)
    original_ids = ids.repeat(search_width, 1)

    if not_allowed_ids is not None:
        grad[:, not_allowed_ids.to(grad.device)] = float("inf")

    topk_ids = (-grad).topk(topk, dim=1).indices

    sampled_ids_pos = torch.argsort(torch.rand((search_width, n_optim_tokens), device=grad.device))[..., :n_replace]
    sampled_ids_val = torch.gather(
        topk_ids[sampled_ids_pos],
        2,
        torch.randint(0, topk, (search_width, n_replace, 1), device=grad.device),
    ).squeeze(2)

    new_ids = original_ids.scatter_(1, sampled_ids_pos, sampled_ids_val)
    return new_ids


def filter_ids(ids: Tensor, tokenizer: transformers.PreTrainedTokenizer):
    """Filters out sequeneces of token ids that change after retokenization."""
    ids_decoded = tokenizer.batch_decode(ids)
    filtered_ids = []

    for i in range(len(ids_decoded)):
        ids_encoded = tokenizer(ids_decoded[i], return_tensors="pt", add_special_tokens=False).to(ids.device)["input_ids"][0]
        if torch.equal(ids[i], ids_encoded):
            filtered_ids.append(ids[i])

    if not filtered_ids:
        raise RuntimeError(
            "No token sequences are the same after decoding and re-encoding. "
            "Consider setting `filter_ids=False` or trying a different `optim_str_init`"
        )

    return torch.stack(filtered_ids)


class GCGThinking:
    def __init__(self, model: transformers.PreTrainedModel, tokenizer: transformers.PreTrainedTokenizer, config: GCGConfig):
        self.model = model
        self.tokenizer = tokenizer
        self.config = config
        self.embedding_layer = model.get_input_embeddings()
        self.not_allowed_ids = None if config.allow_non_ascii else get_nonascii_toks(tokenizer, device=model.device)

        # 预计算思考标签的token IDs，避免重复编码
        self._start_tag_ids = tokenizer.encode(config.thinking_start_tag, add_special_tokens=False)
        self._end_tag_ids = tokenizer.encode(config.thinking_end_tag, add_special_tokens=False)

        # Prefix caching using transformers KV cache mechanism
        self.prefix_cache = None if not config.use_prefix_cache else None  # Will be populated during run

        if model.dtype in (torch.float32, torch.float64):
            logger.warning(f"Model is in {model.dtype}. Use a lower precision data type, if possible, for much faster optimization.")

        if model.device == torch.device("cpu"):
            logger.warning("Model is on the CPU. Use a hardware accelerator for faster optimization.")

        if not tokenizer.chat_template:
            logger.warning("Tokenizer does not have a chat template. Assuming base model and setting chat template to empty.")
            tokenizer.chat_template = "{% for message in messages %}{{ message['content'] }}{% endfor %}"

    def _compute_thinking_length_token_level(self, generated_ids: List[int]) -> int:
        """直接在token id层面计算思考内容长度，避免解码-编码开销

        Args:
            generated_ids: 生成的token id序列

        Returns:
            思考内容的token数量
        """
        # 在生成的token序列中查找标签位置
        start_idx = -1
        end_idx = -1

        # 查找开始标签
        start_tag_len = len(self._start_tag_ids)
        for i in range(len(generated_ids) - start_tag_len + 1):
            if generated_ids[i:i+start_tag_len] == self._start_tag_ids:
                start_idx = i + start_tag_len
                break

        if start_idx == -1:
            return 0  # 没找到开始标签

        # 查找结束标签
        end_tag_len = len(self._end_tag_ids)
        for i in range(start_idx, len(generated_ids) - end_tag_len + 1):
            if generated_ids[i:i+end_tag_len] == self._end_tag_ids:
                end_idx = i
                break

        if end_idx == -1:
            return len(generated_ids) - start_idx  # 没找到结束标签，计算到结尾

        return end_idx - start_idx

    def _setup_prefix_cache(self):
        """Setup KV cache for prefix optimization"""
        if self.prefix_cache is None and self.config.use_prefix_cache:
            with torch.no_grad():
                try:
                    # Pre-compute cache for the prefix (before_str)
                    output = self.model(inputs_embeds=self.before_embeds, use_cache=True)
                    self.prefix_cache = output.past_key_values
                    self.cache_format = "standard"  # Standard transformer format

                    # Test if cache works with a simple call
                    test_embeds = self.after_embeds[:1] if self.after_embeds.shape[0] > 0 else self.embedding_layer(torch.tensor([[1]]))
                    try:
                        self._apply_prefix_cache(self.model, test_embeds, batch_size=1)
                        logger.info("Prefix cache enabled for performance optimization")
                    except Exception as test_error:
                        logger.warning(f"Prefix cache test failed: {test_error}")
                        logger.warning("Disabling prefix cache due to compatibility issues")
                        self.prefix_cache = None

                except Exception as e:
                    logger.warning(f"Failed to setup prefix cache: {e}")
                    logger.warning("Disabling prefix cache due to compatibility issues")
                    self.prefix_cache = None

    def _apply_prefix_cache(self, model, inputs_embeds, batch_size=None):
        """Apply prefix cache if available"""
        if self.prefix_cache is not None:
            try:
                # Only pass the embeddings after the prefix
                if batch_size is None:
                    batch_size = inputs_embeds.shape[0]

                # Check if we can slice the embeddings properly
                if inputs_embeds.shape[1] <= self.before_embeds.shape[1]:
                    # If the input is shorter than expected, fall back to no cache
                    return model(inputs_embeds=inputs_embeds)

                # Extract embeddings after the prefix
                inputs_after_prefix = inputs_embeds[:, self.before_embeds.shape[1]:]

                # Expand prefix cache to match batch size
                expanded_cache = []
                for layer_cache in self.prefix_cache:
                    # layer_cache is a tuple of (key_cache, value_cache)
                    key_cache, value_cache = layer_cache
                    expanded_key = key_cache.expand(batch_size, -1, -1, -1)
                    expanded_value = value_cache.expand(batch_size, -1, -1, -1)
                    expanded_cache.append((expanded_key, expanded_value))

                return model(
                    inputs_embeds=inputs_after_prefix,
                    past_key_values=expanded_cache,
                    use_cache=True
                )
            except Exception as e:
                # If cache application fails, fall back to no cache for this call
                logger.debug(f"Cache application failed, falling back: {e}")
                return model(inputs_embeds=inputs_embeds)
        else:
            return model(inputs_embeds=inputs_embeds)

    def run(self, messages: Union[str, List[dict]], target: str = "") -> GCGResult:
        model = self.model
        tokenizer = self.tokenizer
        config = self.config

        if config.seed is not None:
            set_seed(config.seed)

        if isinstance(messages, str):
            messages = [{"role": "user", "content": messages}]
        else:
            messages = copy.deepcopy(messages)

        # Append the GCG string at the end of the prompt if location not specified
        if not any(["{optim_str}" in d["content"] for d in messages]):
            messages[-1]["content"] = messages[-1]["content"] + "{optim_str}"

        # Apply chat template if available (for models without chat_template like Llama 2)
        if hasattr(tokenizer, 'chat_template') and tokenizer.chat_template:
            template = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        else:
            # For models without chat_template, extract content directly from messages
            if len(messages) == 1 and messages[0]["role"] == "user":
                template = messages[0]["content"]
            else:
                # For multi-turn conversations, concatenate messages
                template = "\n\n".join([f"{msg['role']}: {msg['content']}" for msg in messages])

        if tokenizer.bos_token and template.startswith(tokenizer.bos_token):
            template = template.replace(tokenizer.bos_token, "")
        before_str, after_str = template.split("{optim_str}")

        # Tokenize everything
        before_ids = tokenizer([before_str], padding=False, return_tensors="pt")["input_ids"].to(model.device, torch.int64)
        after_ids = tokenizer([after_str], add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device, torch.int64)

        # Embed everything that doesn't get optimized
        embedding_layer = self.embedding_layer
        before_embeds, after_embeds = [embedding_layer(ids) for ids in (before_ids, after_ids)]

        self.before_embeds = before_embeds
        self.after_embeds = after_embeds

        # Setup prefix cache if enabled
        self._setup_prefix_cache()

        # Initialize the attack buffer
        buffer = self.init_buffer(messages)
        optim_ids = buffer.get_best_ids()

        losses = []
        optim_strings = []

        # Early stopping state tracking
        consecutive_count = 0
        best_overall_loss = float('inf')
        best_overall_ids = None
        best_overall_step = 0
        best_overall_prompt = None  # Store the complete prompt with best optimized string
        max_thinking_length = config.max_generation_tokens - 1

        for step in tqdm(range(config.num_steps)):
            # Compute the token gradient
            optim_ids_onehot_grad = self.compute_token_gradient(optim_ids)

            with torch.no_grad():
                # Sample candidate token sequences based on the token gradient
                sampled_ids = sample_ids_from_grad(
                    optim_ids.squeeze(0),
                    optim_ids_onehot_grad.squeeze(0),
                    config.search_width,
                    config.topk,
                    config.n_replace,
                    not_allowed_ids=self.not_allowed_ids,
                )

                if config.filter_ids:
                    sampled_ids = filter_ids(sampled_ids, tokenizer)

                new_search_width = sampled_ids.shape[0]

                # Compute loss on all candidate sequences
                batch_size = new_search_width if config.batch_size is None else config.batch_size
                input_embeds = torch.cat([
                    before_embeds.repeat(new_search_width, 1, 1),
                    embedding_layer(sampled_ids),
                    after_embeds.repeat(new_search_width, 1, 1),
                ], dim=1)

                loss = find_executable_batch_size(lambda bs, ie: self._compute_candidates_loss(bs, ie, config), batch_size)(input_embeds)
                current_loss = loss.min().item()
                optim_ids = sampled_ids[loss.argmin()].unsqueeze(0)

                # Update the buffer based on the loss
                losses.append(current_loss)
                if buffer.size == 0 or current_loss < buffer.get_highest_loss():
                    buffer.add(current_loss, optim_ids)

            optim_ids = buffer.get_best_ids()
            optim_str = tokenizer.batch_decode(optim_ids)[0]
            optim_strings.append(optim_str)

            # 计算当前最优候选的思考长度
            current_optim_embeds = torch.cat([before_embeds, embedding_layer(optim_ids), after_embeds], dim=1)
            with torch.no_grad():
                current_generated_ids = self._generate_text(current_optim_embeds, max_new_tokens=self.config.max_generation_tokens)
                current_thinking_length = self._compute_thinking_length_token_level(current_generated_ids)

            # Update global best result
            if current_loss < best_overall_loss:
                best_overall_loss = current_loss
                best_overall_ids = optim_ids.clone().to(model.device)  # Ensure on correct device
                best_overall_step = step
                # Save the complete prompt with optimized string
                best_optim_str = tokenizer.batch_decode(optim_ids)[0]
                best_overall_prompt = before_str + best_optim_str + after_str

            # Early stopping logic
            if config.early_stop:
                if current_thinking_length >= max_thinking_length:
                    consecutive_count += 1
                else:
                    consecutive_count = 0

                if consecutive_count >= config.consecutive_threshold:
                    logger.info(f"Early stopping at step {step+1}: {consecutive_count} consecutive times reached max length {max_thinking_length}")
                    logger.info(f"Best loss: {best_overall_loss:.4f} at step {best_overall_step+1}")

                    # Save the complete prompt to a file
                    if best_overall_prompt:
                        prompt_filename = f"best_prompt_step_{best_overall_step+1}_loss_{best_overall_loss:.4f}.txt"
                        with open(prompt_filename, 'w', encoding='utf-8') as f:
                            f.write("=== BEST OPTIMIZED PROMPT ===\n\n")
                            f.write(f"Step: {best_overall_step+1}\n")
                            f.write(f"Loss: {best_overall_loss:.4f}\n")
                            f.write(f"Optimized String: {tokenizer.batch_decode(best_overall_ids)[0]}\n")
                            f.write(f"Thinking Length: {max_thinking_length}\n\n")
                            f.write("--- Complete Prompt ---\n")
                            f.write(best_overall_prompt)
                        logger.info(f"Best prompt saved to: {prompt_filename}")

                    break

            # Output with consecutive count info
            consecutive_info = f"Consecutive: {consecutive_count}/{config.consecutive_threshold}" if config.early_stop else ""
            logger.info(f"Step {step+1}/{config.num_steps} | Thinking Length: {current_thinking_length}/{max_thinking_length} | {consecutive_info} | Best Loss: {buffer.get_lowest_loss():.4f}")

        # Use best result (either from early stopping or normal process)
        if config.early_stop and best_overall_ids is not None:
            final_best_loss = best_overall_loss
            final_best_string = tokenizer.batch_decode(best_overall_ids)[0]
        else:
            min_loss_index = losses.index(min(losses))
            final_best_loss = losses[min_loss_index]
            final_best_string = optim_strings[min_loss_index]

        # 计算最终最佳结果的思考长度
        final_best_ids = tokenizer(final_best_string, add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device)
        final_best_embeds = torch.cat([before_embeds, embedding_layer(final_best_ids), after_embeds], dim=1)
        with torch.no_grad():
            final_generated_ids = self._generate_text(final_best_embeds, max_new_tokens=self.config.max_generation_tokens)
            final_thinking_length = self._compute_thinking_length_token_level(final_generated_ids)

        # 显示最终结果
        logger.info(f"Final Result | Thinking Length: {final_thinking_length} | Best Loss: {final_best_loss:.4f}")

        result = GCGResult(
            best_loss=final_best_loss,
            best_string=final_best_string,
            losses=losses,
            strings=optim_strings,
        )

        return result

    def init_buffer(self, messages: Union[str, List[dict]]) -> AttackBuffer:
        model = self.model
        tokenizer = self.tokenizer
        config = self.config

        if isinstance(messages, str):
            messages = [{"role": "user", "content": messages}]
        else:
            messages = copy.deepcopy(messages)

        # Append the GCG string at the end of the prompt if location not specified
        if not any(["{optim_str}" in d["content"] for d in messages]):
            messages[-1]["content"] = messages[-1]["content"] + "{optim_str}"

        # Apply chat template if available (for models without chat_template like Llama 2)
        if hasattr(tokenizer, 'chat_template') and tokenizer.chat_template:
            template = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        else:
            # For models without chat_template, extract content directly from messages
            if len(messages) == 1 and messages[0]["role"] == "user":
                template = messages[0]["content"]
            else:
                # For multi-turn conversations, concatenate messages
                template = "\n\n".join([f"{msg['role']}: {msg['content']}" for msg in messages])

        if tokenizer.bos_token and template.startswith(tokenizer.bos_token):
            template = template.replace(tokenizer.bos_token, "")
        before_str, after_str = template.split("{optim_str}")

        # Tokenize everything
        before_ids = tokenizer([before_str], padding=False, return_tensors="pt")["input_ids"].to(model.device, torch.int64)
        after_ids = tokenizer([after_str], add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device, torch.int64)

        buffer = AttackBuffer(config.buffer_size)

        if isinstance(config.optim_str_init, str):
            init_optim_ids = tokenizer(config.optim_str_init, add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device)
            if config.buffer_size > 1:
                init_buffer_ids = tokenizer(INIT_CHARS, add_special_tokens=False, return_tensors="pt")["input_ids"].squeeze().to(model.device)
                init_indices = torch.randint(0, init_buffer_ids.shape[0], (config.buffer_size - 1, init_optim_ids.shape[1]))
                init_buffer_ids = torch.cat([init_optim_ids, init_buffer_ids[init_indices]], dim=0)
            else:
                init_buffer_ids = init_optim_ids
        else:
            init_buffer_ids = tokenizer(config.optim_str_init, add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device)

        true_buffer_size = max(1, config.buffer_size)
        init_buffer_embeds = torch.cat([
            self.before_embeds.repeat(true_buffer_size, 1, 1),
            self.embedding_layer(init_buffer_ids),
            self.after_embeds.repeat(true_buffer_size, 1, 1),
        ], dim=1)

        init_buffer_losses = find_executable_batch_size(lambda bs, ie: self._compute_candidates_loss(bs, ie, config), true_buffer_size)(init_buffer_embeds)

        for i in range(true_buffer_size):
            buffer.add(init_buffer_losses[i], init_buffer_ids[[i]])

        # 重新构建嵌入向量用于初始评估
        init_before_embeds, init_after_embeds = [self.embedding_layer(ids) for ids in (before_ids, after_ids)]

        # 显示初始化信息
        best_init_loss = buffer.get_lowest_loss()
        best_init_ids = buffer.get_best_ids()
        best_init_embeds = torch.cat([init_before_embeds, self.embedding_layer(best_init_ids), init_after_embeds], dim=1)
        with torch.no_grad():
            best_init_generated_ids = self._generate_text(best_init_embeds, max_new_tokens=self.config.max_generation_tokens)
            best_init_thinking_length = self._compute_thinking_length_token_level(best_init_generated_ids)

        logger.info(f"Initialization | Thinking Length: {best_init_thinking_length} | Best Loss: {best_init_loss:.4f}")

        return buffer

    def compute_token_gradient(self, optim_ids: Tensor) -> Tensor:
        """Computes gradient based on thinking content length."""
        model = self.model
        embedding_layer = self.embedding_layer

        # Create the one-hot encoding matrix
        optim_ids_onehot = torch.nn.functional.one_hot(optim_ids, num_classes=embedding_layer.num_embeddings)
        optim_ids_onehot = optim_ids_onehot.to(model.device, model.dtype)
        optim_ids_onehot.requires_grad_()

        # Get embeddings
        optim_embeds = optim_ids_onehot @ embedding_layer.weight

        # Create full input
        input_embeds = torch.cat([self.before_embeds, optim_embeds, self.after_embeds], dim=1)

        # Generate text and extract thinking content (优化：直接在token层面计算)
        with torch.no_grad():
            generated_ids = self._generate_text(input_embeds, max_new_tokens=self.config.max_generation_tokens)
            # 直接在token层面计算思考长度，避免解码-编码开销
            thinking_length = self._compute_thinking_length_token_level(generated_ids)
            # Use log transform for loss (range (0, 1], longer thinking = lower loss)
            loss = log_loss_transform(thinking_length, self.config.loss_scale_factor)

        # Create a simple differentiable proxy loss
        # Use the sum of logits as a proxy (this will give gradients)
        proxy_loss = input_embeds.sum() * 0.001  # Small multiplier to keep gradients reasonable

        # Add the real thinking length loss as a constant (doesn't affect gradients but affects the displayed loss)
        thinking_loss = proxy_loss + loss

        optim_ids_onehot_grad = torch.autograd.grad(outputs=[thinking_loss], inputs=[optim_ids_onehot])[0]
        return optim_ids_onehot_grad

    def _generate_text(self, input_embeds: Tensor, max_new_tokens: int = None) -> List[int]:
        """Generate text from input embeddings."""
        if max_new_tokens is None:
            max_new_tokens = self.config.max_generation_tokens

        generated_ids = []
        current_embeds = input_embeds.clone()

        for _ in range(max_new_tokens):
            with torch.no_grad():
                outputs = self._apply_prefix_cache(self.model, current_embeds, batch_size=1)
                logits = outputs.logits[:, -1, :]  # [batch_size, vocab_size]

                # Sample next token
                next_token = torch.multinomial(torch.softmax(logits, dim=-1), 1)  # [batch_size, 1]
                generated_ids.append(next_token[0].item())

                if next_token[0].item() == self.tokenizer.eos_token_id:
                    break

                # Update for next step
                next_token_embed = self.embedding_layer(next_token)  # [batch_size, 1, embed_dim]
                current_embeds = torch.cat([current_embeds, next_token_embed], dim=1)  # [batch_size, seq_len+1, embed_dim]

        return generated_ids

    def _generate_text_batch(self, input_embeds: Tensor, max_new_tokens: int = None) -> List[List[int]]:
        """批量生成文本，支持多个候选同时处理.

        Args:
            input_embeds: [batch_size, seq_len, embed_dim] 批量输入嵌入
            max_new_tokens: 最大生成token数

        Returns:
            List of generated token sequences for each batch item
        """
        if max_new_tokens is None:
            max_new_tokens = self.config.max_generation_tokens

        batch_size = input_embeds.shape[0]
        generated_sequences = [[] for _ in range(batch_size)]
        finished_flags = torch.zeros(batch_size, dtype=torch.bool, device=input_embeds.device)
        current_embeds = input_embeds.clone()

        for step in range(max_new_tokens):
            if finished_flags.all():
                break

            with torch.no_grad():
                outputs = self._apply_prefix_cache(self.model, current_embeds, batch_size=batch_size)
                logits = outputs.logits[:, -1, :]  # [batch_size, vocab_size]

                # Sample next tokens for all active sequences
                probs = torch.softmax(logits, dim=-1)
                next_tokens = torch.multinomial(probs, 1).squeeze(-1)  # [batch_size]

                # Update generated sequences
                for i in range(batch_size):
                    if not finished_flags[i]:
                        token_id = next_tokens[i].item()
                        generated_sequences[i].append(token_id)

                        # Check for EOS token
                        if token_id == self.tokenizer.eos_token_id:
                            finished_flags[i] = True

                # Prepare next step embeddings only for unfinished sequences
                if not finished_flags.all():
                    next_token_embeds = self.embedding_layer(next_tokens.unsqueeze(-1))  # [batch_size, 1, embed_dim]
                    current_embeds = torch.cat([current_embeds, next_token_embeds], dim=1)

        return generated_sequences

    def _compute_candidates_loss(self, search_batch_size: int, input_embeds: Tensor, config: GCGConfig = None) -> Tensor:
        """优化的候选者损失计算，使用批量处理大幅提升性能"""
        if config is None:
            config = self.config

        all_loss = []

        # 根据配置决定使用批量生成还是逐个生成
        if config.use_batch_generation:
            # 计算有效的批量大小，避免OOM
            effective_batch_size = min(search_batch_size, config.max_batch_size)

            for i in range(0, input_embeds.shape[0], effective_batch_size):
                input_embeds_batch = input_embeds[i:i + effective_batch_size]
                current_batch_size = input_embeds_batch.shape[0]

                try:
                    # 使用批量文本生成，一次性处理整个batch
                    with torch.no_grad():
                        # 批量生成所有候选的文本
                        batch_generated_sequences = self._generate_text_batch(
                            input_embeds_batch,
                            max_new_tokens=self.config.max_generation_tokens
                        )

                        # 批量计算思考长度和损失
                        batch_thinking_losses = []
                        for generated_ids in batch_generated_sequences:
                            thinking_length = self._compute_thinking_length_token_level(generated_ids)
                            thinking_loss = log_loss_transform(thinking_length, config.loss_scale_factor)
                            batch_thinking_losses.append(thinking_loss)

                        loss = torch.tensor(batch_thinking_losses, dtype=torch.float32, device=input_embeds.device)
                        all_loss.append(loss)

                except RuntimeError as e:
                    if "out of memory" in str(e):
                        logger.warning(f"OOM in batch generation with size {current_batch_size}, reducing batch size")
                        torch.cuda.empty_cache()  # 清理缓存
                        # 使用更小的批量大小重试
                        smaller_batch_size = max(1, current_batch_size // 2)
                        for j in range(0, current_batch_size, smaller_batch_size):
                            sub_batch = input_embeds_batch[j:j + smaller_batch_size]
                            try:
                                sub_generated_sequences = self._generate_text_batch(
                                    sub_batch, max_new_tokens=self.config.max_generation_tokens
                                )
                                sub_losses = []
                                for gen_ids in sub_generated_sequences:
                                    thinking_length = self._compute_thinking_length_token_level(gen_ids)
                                    sub_loss = log_loss_transform(thinking_length, config.loss_scale_factor)
                                    sub_losses.append(sub_loss)
                                loss = torch.tensor(sub_losses, dtype=torch.float32, device=input_embeds.device)
                                all_loss.append(loss)
                            except Exception:
                                # 最终降级到逐个处理
                                for k in range(sub_batch.shape[0]):
                                    individual_loss = self._compute_single_candidate_loss(
                                        sub_batch[k:k+1], config
                                    )
                                    all_loss.append(individual_loss)
                    else:
                        raise e
        else:
            # 使用原始的逐个处理方式
            for i in range(0, input_embeds.shape[0], search_batch_size):
                input_embeds_batch = input_embeds[i:i + search_batch_size]
                current_batch_size = input_embeds_batch.shape[0]

                batch_thinking_losses = []
                for j in range(current_batch_size):
                    individual_loss = self._compute_single_candidate_loss(
                        input_embeds_batch[j:j+1], config
                    )
                    batch_thinking_losses.append(individual_loss)

                loss = torch.tensor(batch_thinking_losses, dtype=torch.float32, device=input_embeds.device)
                all_loss.append(loss)

        return torch.cat(all_loss, dim=0)

    def _compute_single_candidate_loss(self, candidate_embeds: Tensor, config: GCGConfig) -> Tensor:
        """计算单个候选的损失，用于降级处理"""
        with torch.no_grad():
            try:
                generated_ids = self._generate_text(candidate_embeds, max_new_tokens=self.config.max_generation_tokens)
                thinking_length = self._compute_thinking_length_token_level(generated_ids)
                thinking_loss = log_loss_transform(thinking_length, config.loss_scale_factor)
                return torch.tensor(thinking_loss, dtype=torch.float32, device=candidate_embeds.device)
            except Exception:
                return torch.tensor(0.0, dtype=torch.float32, device=candidate_embeds.device)


def run_gcg_thinking(
    model: transformers.PreTrainedModel,
    tokenizer: transformers.PreTrainedTokenizer,
    messages: Union[str, List[dict]],
    target: str = "",
    config: Optional[GCGConfig] = None,
) -> GCGResult:
    """Generates optimized string to maximize thinking content length."""
    if config is None:
        config = GCGConfig()

    logger.setLevel(getattr(logging, config.verbosity))

    gcg_thinking = GCGThinking(model, tokenizer, config)
    result = gcg_thinking.run(messages, target)
    return result