import copy
import gc
import logging
import queue
import threading
import re

from dataclasses import dataclass
from tqdm import tqdm
from typing import List, Optional, Tuple, Union

import torch
import transformers
from torch import Tensor
from transformers import set_seed
from scipy.stats import spearmanr

from nanogcg.utils import (
    INIT_CHARS,
    configure_pad_token,
    find_executable_batch_size,
    get_nonascii_toks,
    mellowmax,
)

logger = logging.getLogger("nanogcg")
if not logger.hasHandlers():
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s [%(filename)s:%(lineno)d] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


def extract_thinking_content(generated_text: str, start_tag: str = "<thinking>", end_tag: str = "</thinking>") -> str:
    """Extract content between thinking tags from generated text.

    Args:
        generated_text: The text generated by the model
        start_tag: The start tag (default: "<thinking>")
        end_tag: The end tag (default: "</thinking>")

    Returns:
        The content between thinking tags, empty string if no tags found
    """
    # Escape special regex characters in tags
    escaped_start = re.escape(start_tag)
    escaped_end = re.escape(end_tag)

    # Find content between start and end tags
    pattern = f'{escaped_start}(.*?){escaped_end}'
    matches = re.findall(pattern, generated_text, re.DOTALL)

    if not matches:
        return ""

    # Return the longest thinking content if multiple matches exist
    return max(matches, key=len)


@dataclass
class GCGConfig:
    num_steps: int = 250
    optim_str_init: Union[str, List[str]] = "x x x x x x x x x x x x x x x x x x x x"
    search_width: int = 512
    batch_size: int = None
    topk: int = 256
    n_replace: int = 1
    buffer_size: int = 0
    use_mellowmax: bool = False
    mellowmax_alpha: float = 1.0
    early_stop: bool = False
    use_prefix_cache: bool = False  # Disable to avoid complications
    allow_non_ascii: bool = False
    filter_ids: bool = True
    add_space_before_target: bool = False
    seed: int = None
    verbosity: str = "INFO"
    max_generation_tokens: int = 200  # Maximum tokens to generate
    thinking_start_tag: str = "<thinking>"  # Customizable thinking start tag
    thinking_end_tag: str = "</thinking>"    # Customizable thinking end tag


@dataclass
class GCGResult:
    best_loss: float
    best_string: str
    losses: List[float]
    strings: List[str]


class AttackBuffer:
    def __init__(self, size: int):
        self.buffer = []  # elements are (loss: float, optim_ids: Tensor)
        self.size = size

    def add(self, loss: float, optim_ids: Tensor) -> None:
        if self.size == 0:
            self.buffer = [(loss, optim_ids)]
            return

        if len(self.buffer) < self.size:
            self.buffer.append((loss, optim_ids))
        else:
            self.buffer[-1] = (loss, optim_ids)

        self.buffer.sort(key=lambda x: x[0])

    def get_best_ids(self) -> Tensor:
        return self.buffer[0][1]

    def get_lowest_loss(self) -> float:
        return self.buffer[0][0]

    def get_highest_loss(self) -> float:
        return self.buffer[-1][0]

    def log_buffer(self, tokenizer):
        message = "buffer:"
        for loss, ids in self.buffer:
            optim_str = tokenizer.batch_decode(ids)[0]
            optim_str = optim_str.replace("\\", "\\\\")
            optim_str = optim_str.replace("\n", "\\n")
            message += f"\nloss: {loss}" + f" | string: {optim_str}"
        logger.info(message)


def sample_ids_from_grad(
    ids: Tensor,
    grad: Tensor,
    search_width: int,
    topk: int = 256,
    n_replace: int = 1,
    not_allowed_ids: Tensor = False,
):
    """Returns `search_width` combinations of token ids based on the token gradient."""
    n_optim_tokens = len(ids)
    original_ids = ids.repeat(search_width, 1)

    if not_allowed_ids is not None:
        grad[:, not_allowed_ids.to(grad.device)] = float("inf")

    topk_ids = (-grad).topk(topk, dim=1).indices

    sampled_ids_pos = torch.argsort(torch.rand((search_width, n_optim_tokens), device=grad.device))[..., :n_replace]
    sampled_ids_val = torch.gather(
        topk_ids[sampled_ids_pos],
        2,
        torch.randint(0, topk, (search_width, n_replace, 1), device=grad.device),
    ).squeeze(2)

    new_ids = original_ids.scatter_(1, sampled_ids_pos, sampled_ids_val)
    return new_ids


def filter_ids(ids: Tensor, tokenizer: transformers.PreTrainedTokenizer):
    """Filters out sequeneces of token ids that change after retokenization."""
    ids_decoded = tokenizer.batch_decode(ids)
    filtered_ids = []

    for i in range(len(ids_decoded)):
        ids_encoded = tokenizer(ids_decoded[i], return_tensors="pt", add_special_tokens=False).to(ids.device)["input_ids"][0]
        if torch.equal(ids[i], ids_encoded):
            filtered_ids.append(ids[i])

    if not filtered_ids:
        raise RuntimeError(
            "No token sequences are the same after decoding and re-encoding. "
            "Consider setting `filter_ids=False` or trying a different `optim_str_init`"
        )

    return torch.stack(filtered_ids)


class GCGThinking:
    def __init__(self, model: transformers.PreTrainedModel, tokenizer: transformers.PreTrainedTokenizer, config: GCGConfig):
        self.model = model
        self.tokenizer = tokenizer
        self.config = config
        self.embedding_layer = model.get_input_embeddings()
        self.not_allowed_ids = None if config.allow_non_ascii else get_nonascii_toks(tokenizer, device=model.device)

        # 预计算思考标签的token IDs，避免重复编码
        self._start_tag_ids = tokenizer.encode(config.thinking_start_tag, add_special_tokens=False)
        self._end_tag_ids = tokenizer.encode(config.thinking_end_tag, add_special_tokens=False)

        if model.dtype in (torch.float32, torch.float64):
            logger.warning(f"Model is in {model.dtype}. Use a lower precision data type, if possible, for much faster optimization.")

        if model.device == torch.device("cpu"):
            logger.warning("Model is on the CPU. Use a hardware accelerator for faster optimization.")

        if not tokenizer.chat_template:
            logger.warning("Tokenizer does not have a chat template. Assuming base model and setting chat template to empty.")
            tokenizer.chat_template = "{% for message in messages %}{{ message['content'] }}{% endfor %}"

    def _compute_thinking_length_token_level(self, generated_ids: List[int]) -> int:
        """直接在token id层面计算思考内容长度，避免解码-编码开销

        Args:
            generated_ids: 生成的token id序列

        Returns:
            思考内容的token数量
        """
        # 在生成的token序列中查找标签位置
        start_idx = -1
        end_idx = -1

        # 查找开始标签
        start_tag_len = len(self._start_tag_ids)
        for i in range(len(generated_ids) - start_tag_len + 1):
            if generated_ids[i:i+start_tag_len] == self._start_tag_ids:
                start_idx = i + start_tag_len
                break

        if start_idx == -1:
            return 0  # 没找到开始标签

        # 查找结束标签
        end_tag_len = len(self._end_tag_ids)
        for i in range(start_idx, len(generated_ids) - end_tag_len + 1):
            if generated_ids[i:i+end_tag_len] == self._end_tag_ids:
                end_idx = i
                break

        if end_idx == -1:
            return len(generated_ids) - start_idx  # 没找到结束标签，计算到结尾

        return end_idx - start_idx

    def run(self, messages: Union[str, List[dict]], target: str = "") -> GCGResult:
        model = self.model
        tokenizer = self.tokenizer
        config = self.config

        if config.seed is not None:
            set_seed(config.seed)

        if isinstance(messages, str):
            messages = [{"role": "user", "content": messages}]
        else:
            messages = copy.deepcopy(messages)

        # Append the GCG string at the end of the prompt if location not specified
        if not any(["{optim_str}" in d["content"] for d in messages]):
            messages[-1]["content"] = messages[-1]["content"] + "{optim_str}"

        template = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        if tokenizer.bos_token and template.startswith(tokenizer.bos_token):
            template = template.replace(tokenizer.bos_token, "")
        before_str, after_str = template.split("{optim_str}")

        # Tokenize everything
        before_ids = tokenizer([before_str], padding=False, return_tensors="pt")["input_ids"].to(model.device, torch.int64)
        after_ids = tokenizer([after_str], add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device, torch.int64)

        # Embed everything that doesn't get optimized
        embedding_layer = self.embedding_layer
        before_embeds, after_embeds = [embedding_layer(ids) for ids in (before_ids, after_ids)]

        self.before_embeds = before_embeds
        self.after_embeds = after_embeds

        # Initialize the attack buffer
        buffer = self.init_buffer()
        optim_ids = buffer.get_best_ids()

        losses = []
        optim_strings = []

        for _ in tqdm(range(config.num_steps)):
            # Compute the token gradient
            optim_ids_onehot_grad = self.compute_token_gradient(optim_ids)

            with torch.no_grad():
                # Sample candidate token sequences based on the token gradient
                sampled_ids = sample_ids_from_grad(
                    optim_ids.squeeze(0),
                    optim_ids_onehot_grad.squeeze(0),
                    config.search_width,
                    config.topk,
                    config.n_replace,
                    not_allowed_ids=self.not_allowed_ids,
                )

                if config.filter_ids:
                    sampled_ids = filter_ids(sampled_ids, tokenizer)

                new_search_width = sampled_ids.shape[0]

                # Compute loss on all candidate sequences
                batch_size = new_search_width if config.batch_size is None else config.batch_size
                input_embeds = torch.cat([
                    before_embeds.repeat(new_search_width, 1, 1),
                    embedding_layer(sampled_ids),
                    after_embeds.repeat(new_search_width, 1, 1),
                ], dim=1)

                loss = find_executable_batch_size(self._compute_candidates_loss, batch_size)(input_embeds)
                current_loss = loss.min().item()
                optim_ids = sampled_ids[loss.argmin()].unsqueeze(0)

                # Update the buffer based on the loss
                losses.append(current_loss)
                if buffer.size == 0 or current_loss < buffer.get_highest_loss():
                    buffer.add(current_loss, optim_ids)

            optim_ids = buffer.get_best_ids()
            optim_str = tokenizer.batch_decode(optim_ids)[0]
            optim_strings.append(optim_str)

            buffer.log_buffer(tokenizer)

        min_loss_index = losses.index(min(losses))

        result = GCGResult(
            best_loss=losses[min_loss_index],
            best_string=optim_strings[min_loss_index],
            losses=losses,
            strings=optim_strings,
        )

        return result

    def init_buffer(self) -> AttackBuffer:
        model = self.model
        tokenizer = self.tokenizer
        config = self.config

        logger.info(f"Initializing attack buffer of size {config.buffer_size}...")
        buffer = AttackBuffer(config.buffer_size)

        if isinstance(config.optim_str_init, str):
            init_optim_ids = tokenizer(config.optim_str_init, add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device)
            if config.buffer_size > 1:
                init_buffer_ids = tokenizer(INIT_CHARS, add_special_tokens=False, return_tensors="pt")["input_ids"].squeeze().to(model.device)
                init_indices = torch.randint(0, init_buffer_ids.shape[0], (config.buffer_size - 1, init_optim_ids.shape[1]))
                init_buffer_ids = torch.cat([init_optim_ids, init_buffer_ids[init_indices]], dim=0)
            else:
                init_buffer_ids = init_optim_ids
        else:
            init_buffer_ids = tokenizer(config.optim_str_init, add_special_tokens=False, return_tensors="pt")["input_ids"].to(model.device)

        true_buffer_size = max(1, config.buffer_size)
        init_buffer_embeds = torch.cat([
            self.before_embeds.repeat(true_buffer_size, 1, 1),
            self.embedding_layer(init_buffer_ids),
            self.after_embeds.repeat(true_buffer_size, 1, 1),
        ], dim=1)

        init_buffer_losses = find_executable_batch_size(self._compute_candidates_loss, true_buffer_size)(init_buffer_embeds)

        for i in range(true_buffer_size):
            buffer.add(init_buffer_losses[i], init_buffer_ids[[i]])

        buffer.log_buffer(tokenizer)
        logger.info("Initialized attack buffer.")
        return buffer

    def compute_token_gradient(self, optim_ids: Tensor) -> Tensor:
        """Computes gradient based on thinking content length."""
        model = self.model
        embedding_layer = self.embedding_layer

        # Create the one-hot encoding matrix
        optim_ids_onehot = torch.nn.functional.one_hot(optim_ids, num_classes=embedding_layer.num_embeddings)
        optim_ids_onehot = optim_ids_onehot.to(model.device, model.dtype)
        optim_ids_onehot.requires_grad_()

        # Get embeddings
        optim_embeds = optim_ids_onehot @ embedding_layer.weight

        # Create full input
        input_embeds = torch.cat([self.before_embeds, optim_embeds, self.after_embeds], dim=1)

        # Generate text and extract thinking content (优化：直接在token层面计算)
        with torch.no_grad():
            generated_ids = self._generate_text(input_embeds, max_new_tokens=self.config.max_generation_tokens)
            # 直接在token层面计算思考长度，避免解码-编码开销
            thinking_length = self._compute_thinking_length_token_level(generated_ids)
            # Loss is negative thinking length (more tokens = lower loss)
            loss = -thinking_length

        # Create a simple differentiable proxy loss
        # Use the sum of logits as a proxy (this will give gradients)
        proxy_loss = input_embeds.sum() * 0.001  # Small multiplier to keep gradients reasonable

        # Add the real thinking length as a constant (doesn't affect gradients but affects the displayed loss)
        thinking_loss = proxy_loss + loss

        optim_ids_onehot_grad = torch.autograd.grad(outputs=[thinking_loss], inputs=[optim_ids_onehot])[0]
        return optim_ids_onehot_grad

    def _generate_text(self, input_embeds: Tensor, max_new_tokens: int = None) -> List[int]:
        """Generate text from input embeddings."""
        if max_new_tokens is None:
            max_new_tokens = self.config.max_generation_tokens

        generated_ids = []
        current_embeds = input_embeds.clone()

        for _ in range(max_new_tokens):
            with torch.no_grad():
                outputs = self.model(inputs_embeds=current_embeds)
                logits = outputs.logits[:, -1, :]  # [batch_size, vocab_size]

                # Sample next token
                next_token = torch.multinomial(torch.softmax(logits, dim=-1), 1)  # [batch_size, 1]
                generated_ids.append(next_token[0].item())

                if next_token[0].item() == self.tokenizer.eos_token_id:
                    break

                # Update for next step
                next_token_embed = self.embedding_layer(next_token)  # [batch_size, 1, embed_dim]
                current_embeds = torch.cat([current_embeds, next_token_embed], dim=1)  # [batch_size, seq_len+1, embed_dim]

        return generated_ids

    def _compute_candidates_loss(self, search_batch_size: int, input_embeds: Tensor) -> Tensor:
        """优化的候选者损失计算，直接在token层面计算思考内容长度，避免解码-编码开销"""
        total_candidates = input_embeds.shape[0]
        logger.info(f"Evaluating {total_candidates} candidates...")

        all_loss = []

        for i in range(0, input_embeds.shape[0], search_batch_size):
            input_embeds_batch = input_embeds[i:i + search_batch_size]
            current_batch_size = input_embeds_batch.shape[0]

            batch_thinking_losses = []

            for j in range(current_batch_size):
                # Add progress indicator
                if (i + j) % 10 == 0:
                    logger.info(f"Processing candidate {i + j}/{total_candidates}")

                candidate_embeds = input_embeds_batch[j:j+1]

                # Generate text and extract thinking content
                with torch.no_grad():
                    try:
                        # 直接获取token ids，不进行字符串解码
                        generated_ids = self._generate_text(candidate_embeds, max_new_tokens=self.config.max_generation_tokens)

                        # 直接在token层面计算思考长度
                        thinking_length = self._compute_thinking_length_token_level(generated_ids)
                        thinking_loss = -thinking_length

                        # 偶尔解码一次用于日志显示（减少不必要的解码操作）
                        if (i + j) % 20 == 0 and thinking_length > 0:
                            generated_text = self.tokenizer.decode(generated_ids, skip_special_tokens=True)
                            thinking_content = extract_thinking_content(generated_text,
                                                                       self.config.thinking_start_tag,
                                                                       self.config.thinking_end_tag)
                            logger.info(f"Candidate {i+j}: thinking_length={thinking_length}, content_preview={thinking_content[:50]}...")

                    except Exception as e:
                        logger.error(f"Error processing candidate {i+j}: {e}")
                        thinking_loss = 0.0  # Default loss if error occurs

                batch_thinking_losses.append(thinking_loss)

            loss = torch.tensor(batch_thinking_losses, dtype=torch.float32, device=input_embeds.device)
            all_loss.append(loss)

        logger.info(f"Completed evaluating {total_candidates} candidates")
        return torch.cat(all_loss, dim=0)


def run_gcg_thinking(
    model: transformers.PreTrainedModel,
    tokenizer: transformers.PreTrainedTokenizer,
    messages: Union[str, List[dict]],
    target: str = "",
    config: Optional[GCGConfig] = None,
) -> GCGResult:
    """Generates optimized string to maximize thinking content length."""
    if config is None:
        config = GCGConfig()

    logger.setLevel(getattr(logging, config.verbosity))

    gcg_thinking = GCGThinking(model, tokenizer, config)
    result = gcg_thinking.run(messages, target)
    return result